#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "calcom"
name = "cal.com"
description.en = "Appointment scheduling application"
description.fr = "Application de planification de rendez-vous"

version = "6.1.8~ynh1"

maintainers = ["CodeShakingSheep"]

[upstream]
license = "AGPL-3.0"
website = "https://cal.com/"
code = "https://github.com/calcom/cal.com"

[integration]
yunohost = ">= 12.1.28"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "7500M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/calcom/cal.com/archive/refs/tags/v6.1.8.tar.gz"
    sha256 = "d6203df40d5a4fc1c3c8a728ecad8745f2b5e34b6694543076fa8d5b102d5ebf"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 3000

    [resources.apt]
    packages = "postgresql, yarn"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "22"
