#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------------------------------------------------------
    # EVERYTHING PAST THIS POINT IS OPTIONAL AND MOST LIKELY UNNECESSARY FOR NEW APPS
    #--------------------------------------------------------------------------------
   

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------
    
    test_upgrade_from.3f1bdfadf49e3eaf7c95d1ba8821bbf3877c85e0.name = "Upgrade from 6.0.6~ynh1 (before pre-built archive)"
    