#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

key=$(ynh_string_random --length=32)
ynh_app_setting_set --key="key" --value="$key"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_hide_warnings npm install -g corepack
ynh_hide_warnings corepack prepare yarn@latest --activate

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"
ynh_config_add --template=".env" --destination="$install_dir/.env.appStore"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add "$app" --description="Appointment scheduling app" --log="/var/log/$app/$app.log"

#=================================================
# ADD SWAP IF NEEDED
#=================================================
ynh_script_progression "Temporary adding additional swap if needed..."

myynh_add_swap

#=================================================
# INSTALL CAL.COM WITH YARN
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
	ynh_hide_warnings ynh_exec_as_app NODE_OPTIONS="--max-old-space-size=6144" yarn
	ynh_hide_warnings ynh_exec_as_app NODE_OPTIONS="--max-old-space-size=6144" yarn build
	ynh_hide_warnings ynh_exec_as_app yarn clean
popd

# Remove unused files (by checking dockerfile and size found with  du -h --max-depth=1 /var/www/calcom | sort -hr)
ynh_safe_rm $install_dir/.cache
ynh_safe_rm $install_dir/.turbo
ynh_safe_rm $install_dir/.github
ynh_safe_rm $install_dir/docs
ynh_safe_rm $install_dir/.agents

ynh_safe_rm $install_dir/node_modules/.cache
ynh_safe_rm $install_dir/.yarn/cache
ynh_safe_rm $install_dir/apps/web/.next/cache

#=================================================
# REMOVE TEMPORARY SWAP IF ADDED
#=================================================
ynh_script_progression "Remove temporary swap if added..."

ynh_del_swap_fixed

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
