#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE DEPENDENCIES
#=================================================
ynh_script_progression "Restoring dependencies..."

ynh_hide_warnings npm install -g corepack
ynh_hide_warnings corepack prepare yarn@latest --activate

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

ynh_psql_db_shell < ./db.sql

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

yunohost service add "$app" --description="Appointment scheduling app" --log="/var/log/$app/$app.log"

# We don't add swap in CI but well in real installations
if ! ynh_in_ci_tests; then
#=================================================
# ADD SWAP IF NEEDED
#=================================================
ynh_script_progression "Temporarily adding additional swap if needed..."

myynh_add_swap

fi

#=================================================
# INSTALL CAL.COM WITH YARN
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
	ynh_hide_warnings ynh_exec_as_app NODE_OPTIONS="--max-old-space-size=4096" yarn
	ynh_hide_warnings ynh_exec_as_app yarn workspace @calcom/prisma db-deploy
	ynh_hide_warnings ynh_exec_as_app NODE_OPTIONS="--max-old-space-size=8192" yarn build
popd

# We don't add swap in CI but well in real installations
if ! ynh_in_ci_tests; then
#=================================================
# REMOVE TEMPORARY SWAP IF ADDED
#=================================================
ynh_script_progression "Remove temporary swap if added..."

ynh_del_swap

fi

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

### Typically you only have either $app or php-fpm but not both at the same time...
ynh_systemctl --service="$app" --action="start"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
