#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE DEPENDENCIES
#=================================================
ynh_script_progression --message="Restoring dependencies..." --weight=1

ynh_exec_warn_less ynh_install_nodejs --nodejs_version=$nodejs_version

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Restoring the app main directory..." --weight=1

ynh_restore_file --origin_path="$install_dir"

chown -R "$app:www-data" "$install_dir"

#=================================================
# RESTORE THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression --message="Restoring the PostgreSQL database..." --weight=6

ynh_psql_execute_file_as_root --file="./db.sql" --database=$db_name

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Restoring system configurations related to $app..." --weight=1

ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

yunohost service add "$app" --description="Appointment scheduling app" --log="/var/log/$app/$app.log"

#=================================================
# ADD SWAP IF NEEDED
#=================================================
ynh_script_progression --message="Temporary adding additional swap if needed..."

myynh_add_swap

#=================================================
# INSTALL CAL.COM WITH YARN
#=================================================
ynh_script_progression --message="Installing $app..." --weight=1

pushd $install_dir
	ynh_use_nodejs
	ynh_exec_warn_less npm install -g corepack
	ynh_exec_warn_less corepack prepare yarn@latest --activate
	ynh_exec_warn_less ynh_exec_as $app $ynh_node_load_PATH NODE_OPTIONS="--max-old-space-size=4096" yarn
	ynh_exec_warn_less ynh_exec_as $app $ynh_node_load_PATH yarn workspace @calcom/prisma db-deploy
	ynh_exec_warn_less ynh_exec_as $app $ynh_node_load_PATH NODE_OPTIONS="--max-old-space-size=8192" yarn build	
popd

#=================================================
# REMOVE TEMPORARY SWAP IF ADDED
#=================================================
ynh_script_progression --message="Remove temporary swap if added..."

ynh_del_swap_fixed

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression --message="Reloading NGINX web server and $app's service..." --weight=1

### Typically you only have either $app or php-fpm but not both at the same time...
ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/$app/$app.log"

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
