#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

if ynh_app_upgrading_from_version_before 6.2.0~ynh1; then
  	ynh_script_progression "Update keys for $app..."
	key=$(ynh_app_setting_get --app=$app --key=key)
	if [ -n "$key" ]; then
		ynh_app_setting_set --key="nextauth_secret" --value="$nextauth_secret"
		ynh_app_setting_set --key="calendso_encryption_key" --value="$calendso_encryption_key"
		ynh_app_setting_set --key="key" --value=""
	fi
fi

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --source_id="calcom_prebuilt" --dest_dir="$install_dir" --full_replace

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"
ynh_config_add --template=".env.appStore" --destination="$install_dir/.env.appStore"
ynh_config_add --template="api.env" --destination="$install_dir/apps/api/v2/.env"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Appointment scheduling app" --log="/var/log/$app/$app.log"

#=================================================
# UPGRADE DEPENDENCIES WITH YARN
#=================================================
ynh_script_progression "Upgrading $app dependencies..."

pushd $install_dir
	ynh_hide_warnings ynh_exec_as_app NODE_OPTIONS="--max-old-space-size=2048" yarn
	ynh_hide_warnings ynh_exec_as_app yarn workspace @calcom/prisma db-deploy
popd

#=================================================
# CLEAN UP
#=================================================
ynh_script_progression "Cleaning up $app..."

# Remove unused files (by checking dockerfile and size found with  du -h --max-depth=1 /var/www/calcom | sort -hr)
ynh_safe_rm $install_dir/.turbo
ynh_safe_rm $install_dir/.github
ynh_safe_rm $install_dir/docs
ynh_safe_rm $install_dir/agents

ynh_safe_rm $install_dir/node_modules/.cache
ynh_safe_rm $install_dir/.yarn/cache
ynh_safe_rm $install_dir/apps/web/.next/cache

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
