#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --source_id="calcom_prebuilt" --dest_dir="$install_dir"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"
ynh_config_add --template=".env" --destination="$install_dir/.env.appStore"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Appointment scheduling app" --log="/var/log/$app/$app.log"

#=================================================
# CLEAN UP
#=================================================
ynh_script_progression "Cleaning up $app..."

# Remove unused files (by checking dockerfile and size found with  du -h --max-depth=1 /var/www/calcom | sort -hr)
ynh_safe_rm $install_dir/.turbo
ynh_safe_rm $install_dir/.github
ynh_safe_rm $install_dir/docs
ynh_safe_rm $install_dir/agents

ynh_safe_rm $install_dir/node_modules/.cache
ynh_safe_rm $install_dir/.yarn/cache
ynh_safe_rm $install_dir/apps/web/.next/cache

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
