#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"
ynh_config_add --template=".env" --destination="$install_dir/.env.appStore"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Appointment scheduling app" --log="/var/log/$app/$app.log"

# We don't add swap in CI but well in real installations
if ! ynh_in_ci_tests; then
#=================================================
# ADD SWAP IF NEEDED
#=================================================
ynh_script_progression "Temporarily adding additional swap if needed..."

myynh_add_swap

fi

#=================================================
# INSTALL CAL.COM WITH NPM
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
	ynh_hide_warnings ynh_exec_as_app NODE_OPTIONS="--max-old-space-size=4096" yarn
	ynh_hide_warnings ynh_exec_as_app yarn workspace @calcom/prisma db-deploy
	ynh_hide_warnings ynh_exec_as_app NODE_OPTIONS="--max-old-space-size=8192" yarn exec turbo run build --filter=@calcom/web...
popd

# Remove unused files (by checking dockerfile and size found with  du -h --max-depth=1 /var/www/calcom | sort -hr)
ynh_safe_rm $install_dir/.cache
ynh_safe_rm $install_dir/.turbo
ynh_safe_rm $install_dir/.github
ynh_safe_rm $install_dir/docs
ynh_safe_rm $install_dir/.agents

ynh_safe_rm $install_dir/node_modules/.cache
ynh_safe_rm $install_dir/.yarn/cache
ynh_safe_rm $install_dir/apps/web/.next/cache

# We don't add swap in CI but well in real installations
if ! ynh_in_ci_tests; then
#=================================================
# REMOVE TEMPORARY SWAP IF ADDED
#=================================================
ynh_script_progression "Remove temporary swap if added..."

ynh_del_swap

fi

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
